name: Standard Arch Release

on:
  workflow_call:
    inputs:
      java-version:
        description: "The java version"
        default: 17
        required: false
        type: number
      changelog-file:
        description: "Location of the changelog file"
        default: "CHANGELOG.md"
        required: false
        type: string
    secrets:
      saps-token:
        required: false
      nanite-token:
        required: false
      curse-token:
        required: false
jobs:
  release-arch:
    name: Build & release
    uses: nanite/workflows/.github/workflows/standard-release.yml@v1
    with:
      java-version: ${{ inputs.java-version }}
      changelog-file: ${{ inputs.changelog-file }}
      curse-publish-task: "curseforge"
      release-files: ./+(forge|fabric)/build/libs/*+@(mc+([0-9]).+([0-9]).+([0-9])).jar
    secrets: inherit